#!/usr/bin/env bash
src="graphs"
out="/home/resources/Graphs"

# Download program
rm -rf graphs
git clone https://github.com/puzzlef/$src
cd $src

# Download & list graphs
mkdir -p $out && cp -rf data/* $out/
mkdir -p $out/LAW
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/cnr-2000.tar.gz
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/in-2004.tar.gz
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/eu-2005.tar.gz
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/enron.tar.gz
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/amazon-2008.tar.gz
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/ljournal-2008.tar.gz
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/hollywood-2009.tar.gz
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/dblp-2010.tar.gz
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/webbase-2001.tar.gz
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/uk-2002.tar.gz
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/indochina-2004.tar.gz
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/it-2004.tar.gz
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/arabic-2005.tar.gz
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/sk-2005.tar.gz
bash fetch.sh $out/LAW https://suitesparse-collection-website.herokuapp.com/MM/LAW/uk-2005.tar.gz
mkdir -p $out/SNAP
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-Epinions1.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-LiveJournal1.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-Slashdot0811.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-Slashdot0902.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/wiki-Vote.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/email-EuAll.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/email-Enron.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/wiki-Talk.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/cit-HepPh.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/cit-HepTh.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/cit-Patents.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/ca-AstroPh.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/ca-CondMat.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/ca-GrQc.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/ca-HepPh.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/ca-HepTh.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/web-BerkStan.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/web-Google.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/web-NotreDame.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/web-Stanford.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/amazon0302.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/amazon0312.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/amazon0505.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/amazon0601.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/p2p-Gnutella04.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/p2p-Gnutella05.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/p2p-Gnutella06.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/p2p-Gnutella08.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/p2p-Gnutella09.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/p2p-Gnutella24.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/p2p-Gnutella25.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/p2p-Gnutella30.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/p2p-Gnutella31.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/roadNet-CA.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/roadNet-PA.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/roadNet-TX.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/as-735.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/as-Skitter.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/as-caida.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/Oregon-1.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/Oregon-2.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-sign-epinions.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-sign-Slashdot081106.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-sign-Slashdot090216.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-sign-Slashdot090221.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/CollegeMsg.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/com-Amazon.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/com-DBLP.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/com-Friendster.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/com-LiveJournal.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/com-Orkut.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/com-Youtube.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/email-Eu-core.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/email-Eu-core-temporal.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/higgs-twitter.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/loc-Brightkite.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/loc-Gowalla.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-Pokec.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-sign-bitcoin-alpha.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-sign-bitcoin-otc.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/sx-askubuntu.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/sx-mathoverflow.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/sx-stackoverflow.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/sx-superuser.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/twitter7.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/wiki-RfA.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/wiki-talk-temporal.tar.gz
bash fetch.sh $out/SNAP https://suitesparse-collection-website.herokuapp.com/MM/SNAP/wiki-topcats.tar.gz
mkdir -p $out/DIMACS10
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/caidaRouterLevel.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/chesapeake.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/road_central.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/road_usa.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/citationCiteseer.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/coAuthorsCiteseer.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/coAuthorsDBLP.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/coPapersCiteseer.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/coPapersDBLP.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n10.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n11.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n12.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n13.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n14.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n15.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n16.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n17.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n18.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n19.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n20.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n21.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n22.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n23.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n24.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/hugebubbles-00000.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/hugebubbles-00010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/hugebubbles-00020.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/hugetrace-00000.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/hugetrace-00010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/hugetrace-00020.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/hugetric-00000.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/hugetric-00010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/hugetric-00020.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/kron_g500-logn16.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/kron_g500-logn17.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/kron_g500-logn18.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/kron_g500-logn19.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/kron_g500-logn20.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/kron_g500-logn21.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/adaptive.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/channel-500x100x100-b050.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/packing-500x100x100-b050.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/venturiLevel3.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/rgg_n_2_15_s0.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/rgg_n_2_16_s0.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/rgg_n_2_17_s0.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/rgg_n_2_18_s0.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/rgg_n_2_19_s0.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/rgg_n_2_20_s0.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/rgg_n_2_21_s0.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/rgg_n_2_22_s0.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/rgg_n_2_23_s0.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/rgg_n_2_24_s0.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/asia_osm.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/belgium_osm.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/europe_osm.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/germany_osm.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/great-britain_osm.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/italy_osm.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/luxembourg_osm.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/netherlands_osm.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/144.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/598a.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/auto.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/cs4.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/cti.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS1$out.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/fe_4elt2.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/fe_body.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/fe_ocean.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/fe_rotor.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/fe_sphere.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/fe_tooth.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/m14b.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/t60k.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/uk.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/wing.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/wing_nodal.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/G_n_pin_pout.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/preferentialAttachment.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/smallworld.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/333SP.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/AS365.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/M6.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/NACA0015.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/NLR.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ak2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/al2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ar2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/az2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ca2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/co2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ct2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/de2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/fl2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ga2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/hi2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ia2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/id2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/il2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/in2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ks2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ky2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/la2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ma2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/md2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/me2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/mi2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/mn2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/mo2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ms2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/mt2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/nc2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/nd2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ne2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/nh2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/nj2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/nm2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/nv2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ny2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/oh2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ok2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/or2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/pa2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ri2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/sc2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/sd2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/tn2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/tx2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ut2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/va2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vt2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/wa2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/wi2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/wv2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/wy2010.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_barth5_1Ksep_50in_5Kout.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_bcsstk30_500sep_10in_1Kout.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_befref_fxm_2_4_air02.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_bump2_e18_aa01_model1_crew1.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_c-3$ou$out.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_c-6$out_cti_cs4.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vs$out_and_seymourl.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_finan512_scagr7-2c_rlfddd.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_mod2_pgp2_slptsk.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_model1_crew1_cr42_south31.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_msc10848_300sep_100in_1Kout.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_p0291_seymourl_iiasa.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_sctap1-2b_and_seymourl.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_south31_slptsk.tar.gz
bash fetch.sh $out/DIMACS10 https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_vibrobox_scagr7-2c_rlfddd.tar.gz
mkdir -p $out/GAP
bash fetch.sh $out/GAP https://suitesparse-collection-website.herokuapp.com/MM/GAP/GAP-twitter.tar.gz
bash fetch.sh $out/GAP https://suitesparse-collection-website.herokuapp.com/MM/GAP/GAP-web.tar.gz
bash fetch.sh $out/GAP https://suitesparse-collection-website.herokuapp.com/MM/GAP/GAP-road.tar.gz
bash fetch.sh $out/GAP https://suitesparse-collection-website.herokuapp.com/MM/GAP/GAP-kron.tar.gz
bash fetch.sh $out/GAP https://suitesparse-collection-website.herokuapp.com/MM/GAP/GAP-urand.tar.gz
ls --color $out
